// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: descriptor.proto

package proto_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Descriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Descriptor_Message
	//	*Descriptor_Method
	//	*Descriptor_Service
	//	*Descriptor_File
	//	*Descriptor_Field
	//	*Descriptor_Enum
	Kind          isDescriptor_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	mi := &file_descriptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_descriptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_descriptor_proto_rawDescGZIP(), []int{0}
}

func (x *Descriptor) GetKind() isDescriptor_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Descriptor) GetMessage() *descriptorpb.DescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Descriptor) GetMethod() *descriptorpb.MethodDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Method); ok {
			return x.Method
		}
	}
	return nil
}

func (x *Descriptor) GetService() *descriptorpb.ServiceDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Service); ok {
			return x.Service
		}
	}
	return nil
}

func (x *Descriptor) GetFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Descriptor) GetField() *descriptorpb.FieldDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *Descriptor) GetEnum() *descriptorpb.EnumDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Enum); ok {
			return x.Enum
		}
	}
	return nil
}

type isDescriptor_Kind interface {
	isDescriptor_Kind()
}

type Descriptor_Message struct {
	Message *descriptorpb.DescriptorProto `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type Descriptor_Method struct {
	Method *descriptorpb.MethodDescriptorProto `protobuf:"bytes,2,opt,name=method,proto3,oneof"`
}

type Descriptor_Service struct {
	Service *descriptorpb.ServiceDescriptorProto `protobuf:"bytes,3,opt,name=service,proto3,oneof"`
}

type Descriptor_File struct {
	File *descriptorpb.FileDescriptorProto `protobuf:"bytes,4,opt,name=file,proto3,oneof"`
}

type Descriptor_Field struct {
	Field *descriptorpb.FieldDescriptorProto `protobuf:"bytes,5,opt,name=field,proto3,oneof"`
}

type Descriptor_Enum struct {
	Enum *descriptorpb.EnumDescriptorProto `protobuf:"bytes,6,opt,name=enum,proto3,oneof"`
}

func (*Descriptor_Message) isDescriptor_Kind() {}

func (*Descriptor_Method) isDescriptor_Kind() {}

func (*Descriptor_Service) isDescriptor_Kind() {}

func (*Descriptor_File) isDescriptor_Kind() {}

func (*Descriptor_Field) isDescriptor_Kind() {}

func (*Descriptor_Enum) isDescriptor_Kind() {}

var File_descriptor_proto protoreflect.FileDescriptor

const file_descriptor_proto_rawDesc = "" +
	"\n" +
	"\x10descriptor.proto\x12\n" +
	"proto_type\x1a google/protobuf/descriptor.proto\"\x90\x03\n" +
	"\n" +
	"Descriptor\x12<\n" +
	"\amessage\x18\x01 \x01(\v2 .google.protobuf.DescriptorProtoH\x00R\amessage\x12@\n" +
	"\x06method\x18\x02 \x01(\v2&.google.protobuf.MethodDescriptorProtoH\x00R\x06method\x12C\n" +
	"\aservice\x18\x03 \x01(\v2'.google.protobuf.ServiceDescriptorProtoH\x00R\aservice\x12:\n" +
	"\x04file\x18\x04 \x01(\v2$.google.protobuf.FileDescriptorProtoH\x00R\x04file\x12=\n" +
	"\x05field\x18\x05 \x01(\v2%.google.protobuf.FieldDescriptorProtoH\x00R\x05field\x12:\n" +
	"\x04enum\x18\x06 \x01(\v2$.google.protobuf.EnumDescriptorProtoH\x00R\x04enumB\x06\n" +
	"\x04kindB#Z!github.com/accretional/proto-typeb\x06proto3"

var (
	file_descriptor_proto_rawDescOnce sync.Once
	file_descriptor_proto_rawDescData []byte
)

func file_descriptor_proto_rawDescGZIP() []byte {
	file_descriptor_proto_rawDescOnce.Do(func() {
		file_descriptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_descriptor_proto_rawDesc), len(file_descriptor_proto_rawDesc)))
	})
	return file_descriptor_proto_rawDescData
}

var file_descriptor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_descriptor_proto_goTypes = []any{
	(*Descriptor)(nil),                          // 0: proto_type.Descriptor
	(*descriptorpb.DescriptorProto)(nil),        // 1: google.protobuf.DescriptorProto
	(*descriptorpb.MethodDescriptorProto)(nil),  // 2: google.protobuf.MethodDescriptorProto
	(*descriptorpb.ServiceDescriptorProto)(nil), // 3: google.protobuf.ServiceDescriptorProto
	(*descriptorpb.FileDescriptorProto)(nil),    // 4: google.protobuf.FileDescriptorProto
	(*descriptorpb.FieldDescriptorProto)(nil),   // 5: google.protobuf.FieldDescriptorProto
	(*descriptorpb.EnumDescriptorProto)(nil),    // 6: google.protobuf.EnumDescriptorProto
}
var file_descriptor_proto_depIdxs = []int32{
	1, // 0: proto_type.Descriptor.message:type_name -> google.protobuf.DescriptorProto
	2, // 1: proto_type.Descriptor.method:type_name -> google.protobuf.MethodDescriptorProto
	3, // 2: proto_type.Descriptor.service:type_name -> google.protobuf.ServiceDescriptorProto
	4, // 3: proto_type.Descriptor.file:type_name -> google.protobuf.FileDescriptorProto
	5, // 4: proto_type.Descriptor.field:type_name -> google.protobuf.FieldDescriptorProto
	6, // 5: proto_type.Descriptor.enum:type_name -> google.protobuf.EnumDescriptorProto
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_descriptor_proto_init() }
func file_descriptor_proto_init() {
	if File_descriptor_proto != nil {
		return
	}
	file_descriptor_proto_msgTypes[0].OneofWrappers = []any{
		(*Descriptor_Message)(nil),
		(*Descriptor_Method)(nil),
		(*Descriptor_Service)(nil),
		(*Descriptor_File)(nil),
		(*Descriptor_Field)(nil),
		(*Descriptor_Enum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_descriptor_proto_rawDesc), len(file_descriptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_descriptor_proto_goTypes,
		DependencyIndexes: file_descriptor_proto_depIdxs,
		MessageInfos:      file_descriptor_proto_msgTypes,
	}.Build()
	File_descriptor_proto = out.File
	file_descriptor_proto_goTypes = nil
	file_descriptor_proto_depIdxs = nil
}
