// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: typer.proto

package proto_type

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Typer_Resolve_FullMethodName = "/proto_type.Typer/Resolve"
)

// TyperClient is the client API for Typer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Typer resolves named type references to their Descriptor schemas.
// The name in Type must be fully-qualified (e.g. "google.protobuf.Timestamp",
// "sqlite.SelectStmt"). Unknown names return NOT_FOUND.
type TyperClient interface {
	Resolve(ctx context.Context, in *Type, opts ...grpc.CallOption) (*Descriptor, error)
}

type typerClient struct {
	cc grpc.ClientConnInterface
}

func NewTyperClient(cc grpc.ClientConnInterface) TyperClient {
	return &typerClient{cc}
}

func (c *typerClient) Resolve(ctx context.Context, in *Type, opts ...grpc.CallOption) (*Descriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Descriptor)
	err := c.cc.Invoke(ctx, Typer_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TyperServer is the server API for Typer service.
// All implementations must embed UnimplementedTyperServer
// for forward compatibility.
//
// Typer resolves named type references to their Descriptor schemas.
// The name in Type must be fully-qualified (e.g. "google.protobuf.Timestamp",
// "sqlite.SelectStmt"). Unknown names return NOT_FOUND.
type TyperServer interface {
	Resolve(context.Context, *Type) (*Descriptor, error)
	mustEmbedUnimplementedTyperServer()
}

// UnimplementedTyperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTyperServer struct{}

func (UnimplementedTyperServer) Resolve(context.Context, *Type) (*Descriptor, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedTyperServer) mustEmbedUnimplementedTyperServer() {}
func (UnimplementedTyperServer) testEmbeddedByValue()               {}

// UnsafeTyperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TyperServer will
// result in compilation errors.
type UnsafeTyperServer interface {
	mustEmbedUnimplementedTyperServer()
}

func RegisterTyperServer(s grpc.ServiceRegistrar, srv TyperServer) {
	// If the following call panics, it indicates UnimplementedTyperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Typer_ServiceDesc, srv)
}

func _Typer_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TyperServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Typer_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TyperServer).Resolve(ctx, req.(*Type))
	}
	return interceptor(ctx, in, info, handler)
}

// Typer_ServiceDesc is the grpc.ServiceDesc for Typer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Typer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_type.Typer",
	HandlerType: (*TyperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Typer_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "typer.proto",
}
